### ISSUE TITLE
Reported issue by Vikash Kumar 

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/spoon-plugins#114]
I was experimenting with the hpcc plugin for Spoon integration. I have followed the steps as defined in the documentation provided at the plugin page. I am not able to double click any of the hpcc modules and set the settings as specified in the "Getting Started" or "Simple Tutorial" document. I am not sure if I am missing something in my configurations for spoon or whether this is an actual bug. Note that the same bug is popping up for all the mudules that are added through the hpcc plugin for spoon

An unexpected error occurred in Spoon:
org.pentaho.di.ui.job.dialog.JobDialog.setShellImage(Lorg/eclipse/swt/widgets/Shell;Lorg/pentaho/di/job/entry/JobEntryInterface;)V
java.lang.NoSuchMethodError: org.pentaho.di.ui.job.dialog.JobDialog.setShellImage(Lorg/eclipse/swt/widgets/Shell;Lorg/pentaho/di/job/entry/JobEntryInterface;)V
at org.hpccsystems.pentaho.job.eclindex.ECLIndexDialog.open(ECLIndexDialog.java:200)
at org.pentaho.di.ui.spoon.delegates.SpoonJobDelegate.editJobEntry(SpoonJobDelegate.java:255)
at org.pentaho.di.ui.spoon.Spoon.editJobEntry(Spoon.java:8560)
at org.pentaho.di.ui.spoon.job.JobGraph.editEntry(JobGraph.java:2818)
at org.pentaho.di.ui.spoon.job.JobGraph.mouseDoubleClick(JobGraph.java:634)
at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1319)
at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7939)
at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9190)
at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:654)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)

**Comment by jchambers-ln** [comment]
I need to know what version of pentaho this relates to.
